### ISSUE TITLE
高斯推断

### ISSUE THREAD

**Issue by xiaoyaod** [zmhhmz/GPCIS_CVPR2023#3]
您的工作太棒了，对于多维高斯推导 即使看您的补充材料我都十分困惑
冒昧的请问您  可以推荐几本书籍来让我可以更好的理解您的补充材料

**Comment by zmhhmz** [comment]
谢谢您的关注，推荐阅读Williams, Christopher KI, and Carl Edward Rasmussen. Gaussian processes for machine learning. Vol. 2. No. 3. Cambridge, MA: MIT press, 2006.
